pipeline {
    agent any

    stages {
      stage('SCM Checkout') {
        steps {
            git 'https://github.com/Romok1/ansible-config-mgt.git'
        }
      }
      stage('Execute Ansible') {
        steps {
            ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'Ansiblejenk', inventory: '/home/ubuntu/ansible-config-mgt/inventory/dev', playbook: '/home/ubuntu/ansible-config-mgt/static-assignments/common-del.yml'
        }
      }
    }
}   
