pipeline {
    agent any
    environment {
    ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  }

     parameters {
       string(name: 'inventory_file', defaultValue: '${inventory_file}',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages {
      stage('SCM Checkout') {
        steps {
            git(branch: 'main', url:'https://github.com/Romok1/ansible-config-mgt.git')
        }
      }
      stage('change role path') {
        steps {
            sh 'sudo sed -ie "s/roles_path=\/home\/ubuntu\/ansible-config-mgt\/roles/roles_path=\/var\/lib\/jenkins\/workspace\/ansible-config-mgt\/roles/g" ${ANSIBLE_CONFIG}'
        }
      }
      stage('Execute Ansible') {
        steps {
            ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'Ansiblejenk', inventory: '${inventory_file}', playbook: 'playbooks/site.yml'
        }
      }
    }
}   
