---
- name: update dbmysql server
  hosts: dbmysql
  remote_user: ubuntu
  gather_facts: true
  become: yes
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest version
    apt:
      name: wireshark
      state: latest
    when: ansible_os_family == 'Ubuntu'
