---
- name: Include dynamic variables 
  hosts: all

- name: import common file
  import_playbook: ../static-assignments/common.yml 
  tags:
    - always

- name: include env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always
    
- name: import databaser file
  hosts: dbmysql
  import_playbook: ../static-assignments/lbdb.yml

- name: Webserver assignment
  hosts: webservers
  import_playbook: ../static-assignments/webservers.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/lb.yml
  when: load_balancer_is_required 